# Generated by Django 5.1.10 on 2026-07-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0015_workflowrun_observability'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimetric',
            name='estimated_cost_usd',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='aimetric',
            name='type',
            field=models.CharField(choices=[('plan', 'plan'), ('write', 'write'), ('revise', 'revise'), ('format', 'format'), ('promote', 'promote'), ('export', 'export'), ('evaluation', 'evaluation')], max_length=16),
        ),
    ]
