# Generated by Django 5.1.10 on 2026-07-27 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


RULE_SOURCE_TYPES = {'guideline', 'call_snapshot', 'template', 'review_criteria'}
USER_SOURCE_TYPES = {'team_profile'}


def classify_historical_resources(apps, schema_editor):
    AIResource = apps.get_model('ai', 'AIResource')
    AIChunk = apps.get_model('ai', 'AIChunk')
    EvidenceUsage = apps.get_model('ai', 'EvidenceUsage')

    for resource in AIResource.objects.all().iterator():
        if resource.source_type in RULE_SOURCE_TYPES:
            domain = 'grant_rule'
            status = 'pack_draft'
        elif resource.source_type in USER_SOURCE_TYPES and resource.organization_id:
            domain = 'user_evidence'
            status = 'classified'
        else:
            domain = 'unknown'
            status = 'pending_classification'
        AIResource.objects.filter(pk=resource.pk).update(
            knowledge_domain=domain,
            classification_status=status,
        )
        if domain in {'grant_rule', 'user_evidence'}:
            AIChunk.objects.filter(resource_id=resource.pk).update(
                knowledge_domain=domain,
                index_namespace=domain,
            )

    EvidenceUsage.objects.update(evidence_domain='pending_review')


def reset_historical_classification(apps, schema_editor):
    AIResource = apps.get_model('ai', 'AIResource')
    AIChunk = apps.get_model('ai', 'AIChunk')
    EvidenceUsage = apps.get_model('ai', 'EvidenceUsage')
    AIResource.objects.update(knowledge_domain='unknown', classification_status='pending_classification')
    AIChunk.objects.update(knowledge_domain='unknown', index_namespace='')
    EvidenceUsage.objects.update(evidence_domain='pending_review')


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0016_metric_estimated_cost'),
        ('proposals', '0009_proposal_final_markdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=512)),
                ('predicate', models.CharField(max_length=256)),
                ('object', models.TextField()),
                ('fact_type', models.CharField(max_length=128)),
                ('time_range', models.JSONField(default=dict)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('fact_status', models.CharField(choices=[('completed', 'completed'), ('ongoing', 'ongoing'), ('planned', 'planned'), ('uncertain', 'uncertain')], default='uncertain', max_length=16)),
                ('user_role', models.CharField(choices=[('lead', 'lead'), ('first_author', 'first_author'), ('participant', 'participant'), ('team_member', 'team_member'), ('unknown', 'unknown')], default='unknown', max_length=16)),
                ('verification_status', models.CharField(choices=[('extracted', 'extracted'), ('user_confirmed', 'user_confirmed'), ('conflicted', 'conflicted'), ('rejected', 'rejected')], default='extracted', max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='GrantPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('organization_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='aichunk',
            name='chunk_type',
            field=models.CharField(choices=[('unknown', 'unknown'), ('requirement', 'requirement'), ('eligibility', 'eligibility'), ('budget', 'budget'), ('review_criterion', 'review_criterion'), ('section_instruction', 'section_instruction'), ('submission_rule', 'submission_rule'), ('publication', 'publication'), ('project', 'project'), ('patent', 'patent'), ('experiment', 'experiment'), ('dataset', 'dataset'), ('equipment', 'equipment'), ('team_profile', 'team_profile'), ('budget_basis', 'budget_basis')], db_index=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='aichunk',
            name='entity_keys',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='aichunk',
            name='index_namespace',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='aichunk',
            name='index_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='aichunk',
            name='knowledge_domain',
            field=models.CharField(choices=[('unknown', 'unknown'), ('grant_rule', 'grant_rule'), ('user_evidence', 'user_evidence')], db_index=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='aichunk',
            name='parent_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_chunks', to='ai.aichunk'),
        ),
        migrations.AddField(
            model_name='aichunk',
            name='rule_number',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='aichunk',
            name='section_path',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='airesource',
            name='authorization_scope',
            field=models.CharField(choices=[('organization', 'organization'), ('proposal', 'proposal'), ('owner_private', 'owner_private')], default='organization', max_length=32),
        ),
        migrations.AddField(
            model_name='airesource',
            name='classification_status',
            field=models.CharField(choices=[('pending_classification', 'pending_classification'), ('classified', 'classified'), ('pack_draft', 'pack_draft')], db_index=True, default='pending_classification', max_length=32),
        ),
        migrations.AddField(
            model_name='airesource',
            name='knowledge_domain',
            field=models.CharField(choices=[('unknown', 'unknown'), ('grant_rule', 'grant_rule'), ('user_evidence', 'user_evidence')], db_index=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='airesource',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_ai_resources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='airesource',
            name='source_authority',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='airesource',
            name='source_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airesource',
            name='source_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='airesource',
            name='supersedes_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='ai.airesource'),
        ),
        migrations.AddField(
            model_name='evidenceusage',
            name='evidence_domain',
            field=models.CharField(choices=[('grant_rule', 'grant_rule'), ('user_evidence', 'user_evidence'), ('pending_review', 'pending_review')], db_index=True, default='pending_review', max_length=32),
        ),
        migrations.AddField(
            model_name='evidenceusage',
            name='injection_role',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='evidenceusage',
            name='query_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='evidenceusage',
            name='retrieval_run_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('claim_type', models.CharField(default='fact', max_length=64)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='proposals.proposal')),
                ('proposal_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='proposals.proposalsection')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('extracted', 'extracted'), ('user_confirmed', 'user_confirmed'), ('conflicted', 'conflicted'), ('rejected', 'rejected')], max_length=16)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='ai.evidencefact')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_verifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='airesource',
            name='grant_pack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resources', to='ai.grantpack'),
        ),
        migrations.CreateModel(
            name='GrantPackVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('version', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'draft'), ('published', 'published'), ('retired', 'retired')], default='draft', max_length=16)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('last_verified_at', models.DateField(blank=True, null=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ai.grantpack')),
            ],
        ),
        migrations.CreateModel(
            name='GrantPackDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_pack_documents', to='ai.airesource')),
                ('pack_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ai.grantpackversion')),
            ],
        ),
        migrations.CreateModel(
            name='EligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
                ('applicability', models.JSONField(default=dict)),
                ('source_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eligibility_rules', to='ai.aichunk')),
                ('pack_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_rules', to='ai.grantpackversion')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
                ('applicability', models.JSONField(default=dict)),
                ('source_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_rules', to='ai.aichunk')),
                ('pack_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_rules', to='ai.grantpackversion')),
            ],
        ),
        migrations.CreateModel(
            name='GrantProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('program_type', models.CharField(max_length=128)),
                ('region', models.CharField(blank=True, default='', max_length=128)),
                ('authority', models.CharField(max_length=256)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'program_type', 'region'), name='grantprogram_name_type_region_unique')],
            },
        ),
        migrations.AddField(
            model_name='grantpack',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packs', to='ai.grantprogram'),
        ),
        migrations.CreateModel(
            name='GrantRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.CharField(choices=[('content', 'content'), ('format', 'format'), ('eligibility', 'eligibility'), ('budget', 'budget'), ('submission', 'submission')], max_length=32)),
                ('mandatory', models.BooleanField(default=True)),
                ('target_section', models.CharField(blank=True, default='', max_length=128)),
                ('validation_method', models.CharField(blank=True, default='', max_length=128)),
                ('applicability', models.JSONField(default=dict)),
                ('text', models.TextField()),
                ('pack_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='ai.grantpackversion')),
                ('source_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grant_requirements', to='ai.aichunk')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.TextField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pack_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_criteria', to='ai.grantpackversion')),
                ('source_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_criteria', to='ai.aichunk')),
            ],
        ),
        migrations.CreateModel(
            name='RuleConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_priority', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('human_resolution', models.TextField(blank=True, default='')),
                ('conflicting_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicting_conflicts', to='ai.grantrequirement')),
                ('pack_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='ai.grantpackversion')),
                ('primary_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_conflicts', to='ai.grantrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='RuleExtractionReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected')], default='pending', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('pack_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_reviews', to='ai.grantpackversion')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_extraction_reviews', to=settings.AUTH_USER_MODEL)),
                ('source_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rule_extraction_reviews', to='ai.aichunk')),
            ],
        ),
        migrations.CreateModel(
            name='SectionSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('word_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('subsections', models.JSONField(default=list)),
                ('pack_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_schemas', to='ai.grantpackversion')),
                ('source_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_schemas', to='ai.aichunk')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('pack_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_rules', to='ai.grantpackversion')),
                ('source_chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submission_rules', to='ai.aichunk')),
            ],
        ),
        migrations.CreateModel(
            name='UserEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=64)),
                ('authorization_scope', models.CharField(choices=[('organization', 'organization'), ('proposal', 'proposal'), ('owner_private', 'owner_private')], default='organization', max_length=32)),
                ('controlled_summary', models.TextField(blank=True, default='')),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_evidence_records', to='ai.aichunk')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_evidence_records', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_evidence_records', to='proposals.proposal')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_evidence_records', to='ai.airesource')),
            ],
        ),
        migrations.AddField(
            model_name='evidencefact',
            name='user_evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='ai.userevidence'),
        ),
        migrations.CreateModel(
            name='EvidenceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_key', models.CharField(max_length=128)),
                ('entity_type', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=512)),
                ('user_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='ai.userevidence')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_authorizations', to=settings.AUTH_USER_MODEL)),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_authorizations', to='proposals.proposal')),
                ('user_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorizations', to='ai.userevidence')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimEvidenceBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_bindings', to='ai.claim')),
                ('grant_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_bindings', to='ai.grantrequirement')),
                ('user_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claim_bindings', to='ai.userevidence')),
            ],
        ),
        migrations.AddConstraint(
            model_name='grantpackversion',
            constraint=models.UniqueConstraint(fields=('pack', 'year', 'version'), name='grantpackversion_pack_year_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='grantpackdocument',
            constraint=models.UniqueConstraint(fields=('pack_version', 'resource'), name='grantpackdocument_version_resource_unique'),
        ),
        migrations.AddConstraint(
            model_name='sectionschema',
            constraint=models.UniqueConstraint(fields=('pack_version', 'section_key'), name='sectionschema_version_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='evidenceentity',
            constraint=models.UniqueConstraint(fields=('user_evidence', 'entity_key'), name='evidenceentity_evidence_key_unique'),
        ),
        migrations.RunPython(classify_historical_resources, reset_historical_classification),
    ]
