# Generated by Django 5.1.10 on 2026-07-27 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0017_dual_rag_domain_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grantpackdocument',
            name='confidence',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=4),
        ),
        migrations.AddField(
            model_name='grantpackdocument',
            name='document_type',
            field=models.CharField(choices=[('guide', 'guide'), ('template', 'template'), ('notice', 'notice'), ('faq', 'faq'), ('budget', 'budget'), ('review', 'review'), ('form_check', 'form_check'), ('organization_supplement', 'organization_supplement')], default='guide', max_length=32),
        ),
        migrations.AddField(
            model_name='grantpackdocument',
            name='needs_human_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grantpackversion',
            name='detected_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='grantrequirement',
            name='applicable_condition',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='grantrequirement',
            name='extraction_prompt_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='grantrequirement',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grantrequirement',
            name='source_excerpt',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='grantrequirement',
            name='target_sections',
            field=models.ManyToManyField(blank=True, related_name='requirements', to='ai.sectionschema'),
        ),
        migrations.AddField(
            model_name='ruleconflict',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_conflict_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sectionschema',
            name='field_type',
            field=models.CharField(blank=True, default='markdown', max_length=64),
        ),
        migrations.AlterField(
            model_name='grantpackversion',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('extracted', 'extracted'), ('needs_review', 'needs_review'), ('validated', 'validated'), ('published', 'published'), ('superseded', 'superseded'), ('archived', 'archived')], default='draft', max_length=16),
        ),
    ]
