# Generated by Django 5.1.10 on 2026-07-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0018_rule_pack_compiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='aichunk',
            name='embedding_input_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
