# Generated by Django 5.1.10 on 2026-07-27 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0019_domain_indexing'),
        ('proposals', '0009_proposal_final_markdown'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrillSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('active', 'active'), ('completed', 'completed'), ('skipped', 'skipped'), ('blocked', 'blocked'), ('user_ended', 'user_ended')], default='active', max_length=16)),
                ('completion_reason', models.CharField(blank=True, default='', max_length=64)),
                ('question_count', models.PositiveIntegerField(default=0)),
                ('knowledge_snapshot', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grill_sessions', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='GrillDecisionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64)),
                ('topic', models.CharField(max_length=64)),
                ('question', models.TextField()),
                ('question_type', models.CharField(max_length=32)),
                ('depends_on', models.JSONField(default=list)),
                ('blocking', models.BooleanField(default=False)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('recommended_answer', models.TextField(blank=True, default='')),
                ('recommendation_reason', models.TextField(blank=True, default='')),
                ('rule_evidence_ids', models.JSONField(default=list)),
                ('user_evidence_ids', models.JSONField(default=list)),
                ('affected_sections', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('answered', 'answered'), ('skipped', 'skipped'), ('not_applicable', 'not_applicable'), ('auto_resolved', 'auto_resolved')], default='pending', max_length=24)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='ai.grillsession')),
            ],
        ),
        migrations.CreateModel(
            name='AssumptionRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assumption', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'low'), ('high', 'high')], max_length=8)),
                ('status', models.CharField(default='open', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='proposals.proposal')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assumptions', to='ai.grillsession')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('content', models.JSONField(default=dict)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_briefs', to='proposals.proposal')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brief', to='ai.grillsession')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=64)),
                ('value', models.TextField()),
                ('source', models.CharField(default='user_confirmed', max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('affected_sections', models.JSONField(default=list)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='ai.grilldecisionnode')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_decisions', to='proposals.proposal')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='ai.grillsession')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalDecisionLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='ai.proposaldecision')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decision_ledger_entries', to='proposals.proposal')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='ai.grillsession')),
            ],
        ),
        migrations.CreateModel(
            name='ProposalIntakeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=64)),
                ('version', models.PositiveIntegerField(default=1)),
                ('schema_version', models.CharField(default='v1', max_length=16)),
                ('rule_readiness', models.CharField(choices=[('verified_pack', 'verified_pack'), ('uploaded_pending', 'uploaded_pending'), ('generic_fallback', 'generic_fallback'), ('missing_blocking', 'missing_blocking')], max_length=32)),
                ('content_maturity', models.CharField(choices=[('none', 'none'), ('rough_notes', 'rough_notes'), ('outline', 'outline'), ('partial_draft', 'partial_draft'), ('full_draft', 'full_draft')], max_length=32)),
                ('evidence_readiness', models.CharField(choices=[('none', 'none'), ('partial', 'partial'), ('sufficient', 'sufficient'), ('verified', 'verified')], max_length=32)),
                ('task_mode', models.CharField(choices=[('polish_existing', 'polish_existing'), ('refine_outline', 'refine_outline'), ('plan_from_scratch', 'plan_from_scratch')], max_length=32)),
                ('quality_level', models.CharField(choices=[('quick', 'quick'), ('standard', 'standard'), ('deep', 'deep')], max_length=16)),
                ('detected_inputs', models.JSONField(default=dict)),
                ('user_overrides', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intake_profiles', to='proposals.proposal')),
            ],
        ),
        migrations.AddField(
            model_name='grillsession',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grill_sessions', to='ai.proposalintakeprofile'),
        ),
        migrations.CreateModel(
            name='ProposalWorkPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('grill_mode', models.CharField(max_length=32)),
                ('question_budget', models.PositiveIntegerField(default=5)),
                ('preserve_user_structure', models.BooleanField(default=False)),
                ('planning_mode', models.CharField(max_length=32)),
                ('writing_mode', models.CharField(max_length=32)),
                ('allowed_assumptions', models.JSONField(default=list)),
                ('enabled_reviewers', models.JSONField(default=list)),
                ('max_auto_revisions', models.PositiveIntegerField(default=0)),
                ('blocking_policy', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_policy', to='ai.proposalintakeprofile')),
            ],
        ),
        migrations.AddField(
            model_name='grillsession',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grill_sessions', to='ai.proposalworkpolicy'),
        ),
        migrations.CreateModel(
            name='GrantGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=256)),
                ('definition', models.TextField()),
                ('source', models.CharField(default='user_confirmed', max_length=32)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_glossary', to='proposals.proposal')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('proposal', 'term'), name='grantglossary_proposal_term_unique')],
            },
        ),
        migrations.CreateModel(
            name='GrillAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('adopt_recommendation', 'adopt_recommendation'), ('modify_and_adopt', 'modify_and_adopt'), ('custom', 'custom'), ('skip', 'skip'), ('end', 'end')], max_length=32)),
                ('answer', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grill_answers', to=settings.AUTH_USER_MODEL)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='ai.grilldecisionnode')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('node', 'idempotency_key'), name='grillanswer_node_idempotency_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='grilldecisionnode',
            index=models.Index(fields=['session', 'status', 'priority'], name='grillnode_session_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='grilldecisionnode',
            constraint=models.UniqueConstraint(fields=('session', 'node_id'), name='grillnode_session_nodeid_unique'),
        ),
        migrations.AddConstraint(
            model_name='proposalintakeprofile',
            constraint=models.UniqueConstraint(fields=('proposal', 'version'), name='intakeprofile_proposal_version_unique'),
        ),
    ]
