# Generated by Django 5.1.10 on 2026-07-27 10:17

import django.db.models.deletion
from django.db import migrations, models


def normalize_legacy_claim_values(apps, schema_editor):
    Claim = apps.get_model('ai', 'Claim')
    Claim.objects.filter(claim_type='fact').update(claim_type='factual')
    Claim.objects.filter(status='draft').update(status='planned')


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0020_phase7_intake_grill'),
        ('proposals', '0009_proposal_final_markdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='addressed_requirements',
            field=models.ManyToManyField(blank=True, related_name='addressing_claims', to='ai.grantrequirement'),
        ),
        migrations.AddField(
            model_name='claim',
            name='proposal_decisions',
            field=models.ManyToManyField(blank=True, related_name='claims', to='ai.proposaldecision'),
        ),
        migrations.AddField(
            model_name='claim',
            name='risk_level',
            field=models.CharField(default='low', max_length=16),
        ),
        migrations.AddField(
            model_name='claim',
            name='source_mode',
            field=models.CharField(default='confirmed_brief', max_length=32),
        ),
        migrations.AddField(
            model_name='claimevidencebinding',
            name='reviewer_status',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='claimevidencebinding',
            name='support_strength',
            field=models.CharField(default='partial', max_length=16),
        ),
        migrations.AddField(
            model_name='claimevidencebinding',
            name='support_type',
            field=models.CharField(default='support', max_length=32),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_type',
            field=models.CharField(choices=[('factual', 'factual'), ('numerical', 'numerical'), ('interpretive', 'interpretive'), ('proposed', 'proposed'), ('comparative', 'comparative'), ('eligibility', 'eligibility'), ('unsupported', 'unsupported')], default='unsupported', max_length=64),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('planned', 'planned'), ('retrieved', 'retrieved'), ('drafted', 'drafted'), ('verified', 'verified'), ('human_approved', 'human_approved'), ('locked', 'locked'), ('missing_evidence', 'missing_evidence'), ('partial_support', 'partial_support'), ('conflicted', 'conflicted'), ('rejected', 'rejected'), ('outdated', 'outdated')], default='planned', max_length=32),
        ),
        migrations.RunPython(normalize_legacy_claim_values, migrations.RunPython.noop),
        migrations.CreateModel(
            name='ClaimIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('factual', 'factual'), ('numerical', 'numerical'), ('interpretive', 'interpretive'), ('proposed', 'proposed'), ('comparative', 'comparative'), ('eligibility', 'eligibility'), ('unsupported', 'unsupported')], max_length=32)),
                ('text', models.TextField()),
                ('risk_level', models.CharField(default='low', max_length=16)),
                ('addressed_requirements', models.ManyToManyField(blank=True, related_name='claim_intents', to='ai.grantrequirement')),
                ('proposal_decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_intents', to='ai.proposaldecision')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planning_mode', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('planned', 'planned'), ('needs_replan', 'needs_replan'), ('confirmed', 'confirmed'), ('superseded', 'superseded')], default='planned', max_length=32)),
                ('requirement_gaps', models.JSONField(default=list)),
                ('evidence_gaps', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_plans', to='ai.proposalbrief')),
                ('pack_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_plans', to='ai.grantpackversion')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claim_plans', to='ai.proposalworkpolicy')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_plans', to='proposals.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='SectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=0)),
                ('claim_intents', models.JSONField(default=list)),
                ('questions', models.JSONField(default=list)),
                ('claim_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_plans', to='ai.claimplan')),
                ('proposal_decisions', models.ManyToManyField(blank=True, related_name='section_plans', to='ai.proposaldecision')),
                ('section_schema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_sections', to='ai.sectionschema')),
                ('target_requirements', models.ManyToManyField(blank=True, related_name='section_plans', to='ai.grantrequirement')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('required_for_claim_type', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('open', 'open'), ('satisfied', 'satisfied'), ('blocked', 'blocked')], default='open', max_length=16)),
                ('claim_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_needs', to='ai.claimintent')),
                ('section_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_needs', to='ai.sectionplan')),
            ],
        ),
        migrations.AddField(
            model_name='claimintent',
            name='section_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_intents_records', to='ai.sectionplan'),
        ),
        migrations.AddConstraint(
            model_name='sectionplan',
            constraint=models.UniqueConstraint(fields=('claim_plan', 'section_key'), name='sectionplan_plan_key_unique'),
        ),
    ]
