# Generated by Django 5.1.10 on 2026-07-27 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0021_phase8_claim_planning'),
        ('proposals', '0009_proposal_final_markdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimSentenceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
                ('text_snapshot', models.TextField()),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence_mappings', to='ai.claim')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_sentence_mappings', to='proposals.proposalsection')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('rule', 'rule'), ('fact', 'fact'), ('cross_system', 'cross_system')], max_length=32)),
                ('code', models.CharField(max_length=64)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'low'), ('high', 'high')], max_length=8)),
                ('auto_fixable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('open', 'open'), ('auto_fixed', 'auto_fixed'), ('needs_user_decision', 'needs_user_decision'), ('resolved', 'resolved')], default='open', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_issues', to='ai.claim')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_issues', to='proposals.proposal')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_issues', to='ai.grantrequirement')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_issues', to='proposals.proposalsection')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='ai.proposaldecision')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_decisions', to='ai.grillsession')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_decision', to='ai.reviewissue')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(max_length=64)),
                ('before_text', models.TextField()),
                ('after_text', models.TextField()),
                ('diff', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='ai.reviewissue')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_revisions', to='proposals.proposalsection')),
            ],
        ),
        migrations.CreateModel(
            name='SectionWriterRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writing_mode', models.CharField(max_length=32)),
                ('rule_context', models.JSONField(default=list)),
                ('user_evidence_context', models.JSONField(default=list)),
                ('protected_facts', models.JSONField(default=list)),
                ('missing_evidence', models.JSONField(default=list)),
                ('proposal_brief', models.JSONField(default=dict)),
                ('work_policy', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer_runs', to='proposals.proposalsection')),
                ('section_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='writer_runs', to='ai.sectionplan')),
            ],
        ),
    ]
