/** AUTO-GENERATED: DO NOT EDIT. Source: locales/en.yml */
export const KEYS = {
  'ai.revise.locked': "Section is locked. Unlock before revising.",
  'errors.account.invalid_email': "请输入有效的邮箱地址。",
  'errors.account.invalid_username': "用户名需为 2 至 64 个字符，只能包含字母、数字、下划线、点和连字符。",
  'errors.account.no_changes': "请先修改资料再保存。",
  'errors.account.username_taken': "该用户名已被使用。",
  'errors.ai.not_found': "Requested resource not found.",
  'errors.generic.unexpected': "Something went wrong. Please try again.",
  'ui.account.buttons.save': "保存资料",
  'ui.account.heading': "账户设置",
  'ui.account.labels.email': "邮箱",
  'ui.account.labels.first_name': "名字",
  'ui.account.labels.last_name': "姓氏",
  'ui.account.labels.username': "用户名",
  'ui.account.status.saved': "资料已保存。",
  'ui.auth.app_name': "FoundationPal",
  'ui.auth.confirmation_stub': "Confirmation email sent to your address (stub). Name: {name}",
  'ui.auth.continue_button': "Continue",
  'ui.auth.create_account_button': "Create an account",
  'ui.auth.debug_email_placeholder': "debug: you@example.com",
  'ui.auth.debug_google_button': "Debug Google Login",
  'ui.auth.debug_oauth_failed': "Debug OAuth failed",
  'ui.auth.enter_email_debug_oauth': "Enter email for debug OAuth",
  'ui.auth.invite_accept_button': "Accept invite",
  'ui.auth.invite_accept_failed_prefix': "Invite accept failed:",
  'ui.auth.invite_accept_pending_button': "Accept pending invite",
  'ui.auth.invite_accept_success': "Invite accepted",
  'ui.auth.invite_banner_detected': "Organization invite detected.",
  'ui.auth.invite_not_now_button': "Not now",
  'ui.auth.invite_token_placeholder': "Invite token (optional)",
  'ui.auth.login_button': "Login",
  'ui.auth.login_heading': "Login",
  'ui.auth.name_placeholder': "Your name",
  'ui.auth.org_name_placeholder': "Organization name (or leave blank if using an invite)",
  'ui.auth.password_placeholder': "password",
  'ui.auth.registration_failed_prefix': "Registration failed:",
  'ui.auth.registration_heading': "Complete your registration",
  'ui.auth.sign_in_facebook': "Sign in with Facebook",
  'ui.auth.sign_in_failed_generic': "Sign-in failed. Please try again.",
  'ui.auth.sign_in_github': "Sign in with GitHub",
  'ui.auth.sign_in_google': "Sign in with Google",
  'ui.auth.signing_in': "Signing you in…",
  'ui.auth.username_placeholder': "username",
  'ui.author_panel.approve_save_button': "Approve & Save",
  'ui.author_panel.approved_sections': "Approved sections",
  'ui.author_panel.attach_files_label': "Attach files (pdf, docx, txt, images)",
  'ui.author_panel.author_label': "Author",
  'ui.author_panel.by_user': " by {username}",
  'ui.author_panel.change_request_placeholder': "Change request (optional)",
  'ui.author_panel.created_label': "Created",
  'ui.author_panel.draft_label': "Draft",
  'ui.author_panel.errors.final_format_failed': "Final format failed",
  'ui.author_panel.errors.plan_load_failed': "Failed to load plan",
  'ui.author_panel.errors.revise_failed': "Revise failed",
  'ui.author_panel.errors.save_failed': "保存失败，请稍后重试。",
  'ui.author_panel.errors.save_note_failed': "Save note failed",
  'ui.author_panel.errors.write_failed': "Write failed",
  'ui.author_panel.files_for_section': "Files for this section",
  'ui.author_panel.final_formatting_heading': "Final formatting (runs after all sections are approved)",
  'ui.author_panel.formatted_preview': "Formatted preview",
  'ui.author_panel.internal_note_label': "Internal note",
  'ui.author_panel.just_now': " (just now)",
  'ui.author_panel.last_edited_label': "Last edited",
  'ui.author_panel.last_saved': "Last saved {time}",
  'ui.author_panel.note_placeholder': "Add a note for collaborators",
  'ui.author_panel.ocr_preview': "OCR preview",
  'ui.author_panel.plan_proposal_heading': "Plan your proposal",
  'ui.author_panel.previous_label': "Previous",
  'ui.author_panel.revise_button': "Revise",
  'ui.author_panel.run_final_formatting': "Run Final Formatting",
  'ui.author_panel.save_note_button': "Save Note",
  'ui.author_panel.schema_label': "Schema: {version}",
  'ui.author_panel.section_counter': "Section {current} / {total}:",
  'ui.author_panel.start_button': "Start",
  'ui.author_panel.template_hint_placeholder': "Template hint (optional)",
  'ui.author_panel.untitled': "Untitled",
  'ui.author_panel.upload_failed': "Upload failed",
  'ui.author_panel.uploading': "Uploading…",
  'ui.author_panel.working': "Working…",
  'ui.author_panel.write_button': "Write",
  'ui.buttons.approve_save': "Approve & Save",
  'ui.buttons.archive': "Archive",
  'ui.buttons.close_author': "Close Author",
  'ui.buttons.export': "Export",
  'ui.buttons.open_author': "Open Author",
  'ui.buttons.revise': "Revise",
  'ui.buttons.run_final_formatting': "Run Final Formatting",
  'ui.buttons.save_note': "Save Note",
  'ui.buttons.start': "Start",
  'ui.buttons.unarchive': "Unarchive",
  'ui.buttons.write': "Write",
  'ui.common.files_for_section': "Files for this section",
  'ui.common.loading': "Loading…",
  'ui.common.ocr_preview': "OCR preview",
  'ui.common.untitled': "Untitled",
  'ui.common.upload_failed': "Upload failed",
  'ui.common.uploading': "Uploading…",
  'ui.common.working': "Working…",
  'ui.dashboard.archive_button': "Archive",
  'ui.dashboard.close_author': "Close Author",
  'ui.dashboard.export_button': "Export",
  'ui.dashboard.export_failed': "Export failed: {message}",
  'ui.dashboard.export_still_processing': "Export still processing; try again later",
  'ui.dashboard.exporting': "Exporting…",
  'ui.dashboard.format_docx': "DOCX",
  'ui.dashboard.format_md': "Markdown",
  'ui.dashboard.format_pdf': "PDF",
  'ui.dashboard.heading': "My Proposals",
  'ui.dashboard.loading': "Loading…",
  'ui.dashboard.new_button': "New",
  'ui.dashboard.open_author': "Open Author",
  'ui.dashboard.org_id_placeholder': "Org ID (optional)",
  'ui.dashboard.proposal_id_prefix': "#",
  'ui.dashboard.state_archived': "archived",
  'ui.dashboard.state_draft': "draft",
  'ui.dashboard.unarchive_button': "Unarchive",
  'ui.dashboard.untitled': "Untitled",
  'ui.diff.draft': "Draft",
  'ui.diff.heading': "Changes",
  'ui.diff.previous': "Previous",
  'ui.errors.export_failed': "Export failed",
  'ui.errors.export_still_processing': "Export still processing; try again later",
  'ui.errors.final_format_failed': "Final format failed",
  'ui.errors.plan_load_failed': "Failed to load plan",
  'ui.errors.revise_failed': "Revise failed",
  'ui.errors.save_failed': "Save failed",
  'ui.errors.save_note_failed': "Save note failed",
  'ui.errors.write_failed': "Write failed",
  'ui.labels.approved_sections': "Approved sections",
  'ui.labels.attach_files': "Attach files (pdf, docx, txt, images)",
  'ui.labels.author': "Author",
  'ui.labels.change_request_optional': "Change request (optional)",
  'ui.labels.created': "Created",
  'ui.labels.final_formatting_intro': "Final formatting (runs after all sections are approved)",
  'ui.labels.formatted_preview': "Formatted preview",
  'ui.labels.internal_note': "Internal note",
  'ui.labels.last_edited': "Last edited",
  'ui.labels.plan_proposal': "Plan your proposal",
  'ui.labels.section_counter': "Section {current} / {total}:",
  'ui.labels.template_hint_optional': "Template hint (optional)",
  'ui.memory.empty': "No suggestions yet",
  'ui.memory.error': "Failed to load suggestions",
  'ui.memory.heading': "Memory suggestions",
  'ui.memory.insert': "Insert",
  'ui.memory.loading': "Loading…",
  'ui.memory.refresh': "Refresh",
  'ui.memory.uses': "uses: {count}",
  'ui.nav.dashboard': "Dashboard",
  'ui.orgs.confirm_delete': "确认删除工作区？",
  'ui.orgs.create_button': "新建工作区",
  'ui.orgs.delete_button': "删除",
  'ui.orgs.description_placeholder': "说明，可选",
  'ui.orgs.heading': "工作区管理",
  'ui.orgs.hide_button': "收起",
  'ui.orgs.manage_button': "管理",
  'ui.orgs.member_role_admin': "管理员",
  'ui.orgs.member_role_member': "成员",
  'ui.orgs.members_heading': "成员",
  'ui.orgs.new_name_placeholder': "工作区名称",
  'ui.orgs.use_button': "使用此工作区",
  'ui.proposals_ui.last_saved': "Last saved {time}",
  'ui.proposals_ui.schema': "Schema: {version}",
  'ui.proposals.empty_state': "No proposals yet",
} as const;

export type Key = keyof typeof KEYS;

/**
 * Translate a key. If the key is unexpectedly missing (should not happen if generated),
 * returns the key string itself to avoid runtime crashes.
 * Supports simple {placeholder} interpolation.
 */
export function t(key: Key | string, params?: Record<string, string | number>): string {
  if (!(key in KEYS)) return String(key);
  let msg = KEYS[key as Key];
  if (!params) return msg;
  return msg.replace(/\{(\w+)\}/g, (_, p) => (p in params ? String(params[p]) : '{' + p + '}'));
}
